module.exports = {
    ActionTypes: {
        FETCH_CALENDARS: 'FETCH_CALENDARS',
        RECEIVE_CALENDARS: 'RECEIVE_CALENDARS',
        DISABLE_CALENDAR: 'DISABLE_CALENDAR',
        ENABLE_CALENDAR: 'ENABLE_CALENDAR'
    }
};