name: Upgrading
description: When having trouble upgrading Baikal
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have used the search function for [**OPEN**](https://github.com/sabre-io/Baikal/issues) issues to see if someone else has already submitted the same feature request.
          required: true
        - label: I have **also** used the search function for [**CLOSED**](https://github.com/sabre-io/Baikal/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature is already implemented and just waiting to be released.
          required: true
        - label: I will describe the problem with as much detail as possible.
          required: true
        - label: This is not about the docker image. In that case, contact the authors of the docker image.
          required: true
  - type: checkboxes
    id: checklist_upgrading
    attributes:
      label: Common problems checklist
      options:
        - label: I have installed the release zip, not the source code zip
          required: true
        - label: I have moved the whole, untouched `Specific` and `config` folders to the new installation
          required: true
  - type: input
    id: version
    attributes:
      label: Baikal version before
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: version_after
    attributes:
      label: Baikal version after
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: php_version
    attributes:
      label: PHP version
    validations:
      required: true
  - type: textarea
    id: problems
    attributes:
      label: Problem you are having
