<?php

namespace Baikal\ModelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Baikal\ModelBundle\Entity\User;

/**
 * UserPrincipalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPrincipalRepository extends EntityRepository {

    public function findByUser(User $user) {
        return $this->createQueryBuilder('o')
                    ->where('o.uri = :uri OR o.uri LIKE :urilike')
                    ->setParameter('uri', 'principals/' . $user->getUsername())
                    ->setParameter('urilike', 'principals/' . $user->getUsername() . '/%')
                    ->getQuery()
                    ->getResult();
    }
}
