name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP and Install Composer Dependencies
        uses: ./.github/actions/build
        with:
          php-version: 8.2
      - name: Build assets
        run: make build-assets
      - name: Build dist
        run: make dist
